version: '3.8'

services:
  frontend:
    image: ${DOCKER_USERNAME}/hacker-news-frontend:latest
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000

  backend:
    image: ${DOCKER_USERNAME}/hacker-news-backend:latest
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
